# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import video_server_pb2 as video__server__pb2


class FrameServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DumpFrame = channel.stream_unary(
        '/FrameService/DumpFrame',
        request_serializer=video__server__pb2.FrameInfo.SerializeToString,
        response_deserializer=video__server__pb2.FrameResponse.FromString,
        )


class FrameServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def DumpFrame(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FrameServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DumpFrame': grpc.stream_unary_rpc_method_handler(
          servicer.DumpFrame,
          request_deserializer=video__server__pb2.FrameInfo.FromString,
          response_serializer=video__server__pb2.FrameResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'FrameService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
