# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video_server.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='video_server.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12video_server.proto\"\x1a\n\tFrameInfo\x12\r\n\x05image\x18\x01 \x01(\x0c\"\x1e\n\rFrameResponse\x12\r\n\x05reply\x18\x01 \x01(\t2h\n\x0c\x46rameService\x12+\n\tDumpFrame\x12\n.FrameInfo\x1a\x0e.FrameResponse\"\x00(\x01\x12+\n\x0bReturnFrame\x12\n.FrameInfo\x1a\x0e.FrameResponse\"\x00\x62\x06proto3')
)




_FRAMEINFO = _descriptor.Descriptor(
  name='FrameInfo',
  full_name='FrameInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='FrameInfo.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=48,
)


_FRAMERESPONSE = _descriptor.Descriptor(
  name='FrameResponse',
  full_name='FrameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='FrameResponse.reply', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=80,
)

DESCRIPTOR.message_types_by_name['FrameInfo'] = _FRAMEINFO
DESCRIPTOR.message_types_by_name['FrameResponse'] = _FRAMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FrameInfo = _reflection.GeneratedProtocolMessageType('FrameInfo', (_message.Message,), {
  'DESCRIPTOR' : _FRAMEINFO,
  '__module__' : 'video_server_pb2'
  # @@protoc_insertion_point(class_scope:FrameInfo)
  })
_sym_db.RegisterMessage(FrameInfo)

FrameResponse = _reflection.GeneratedProtocolMessageType('FrameResponse', (_message.Message,), {
  'DESCRIPTOR' : _FRAMERESPONSE,
  '__module__' : 'video_server_pb2'
  # @@protoc_insertion_point(class_scope:FrameResponse)
  })
_sym_db.RegisterMessage(FrameResponse)



_FRAMESERVICE = _descriptor.ServiceDescriptor(
  name='FrameService',
  full_name='FrameService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=82,
  serialized_end=186,
  methods=[
  _descriptor.MethodDescriptor(
    name='DumpFrame',
    full_name='FrameService.DumpFrame',
    index=0,
    containing_service=None,
    input_type=_FRAMEINFO,
    output_type=_FRAMERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ReturnFrame',
    full_name='FrameService.ReturnFrame',
    index=1,
    containing_service=None,
    input_type=_FRAMEINFO,
    output_type=_FRAMERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FRAMESERVICE)

DESCRIPTOR.services_by_name['FrameService'] = _FRAMESERVICE

# @@protoc_insertion_point(module_scope)
